services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"   # REST API
    volumes:
      - qdrant_data:/qdrant/storage

  ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai
    env_file: .env
    environment:
      - QDRANT_URL=http://qdrant:6333   # Override localhost → Docker internal DNS
    ports:
      - "3000:3000"
    depends_on:
      qdrant:
        condition: service_started

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: ui
    ports:
      - "80:80"
#    depends_on:
#      ai:
#        condition: service_started

  seeder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seeder
    env_file: .env
    environment:
      - QDRANT_URL=http://qdrant:6333
    command: sh -c "node dist/scripts/fetch-articles.js && node dist/scripts/ingest.js"
    depends_on:
      qdrant:
        condition: service_started
    profiles:
      - seed

volumes:
  qdrant_data:
